
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    lua_check_client_abort on;  # Detect client aborts
    lua_code_cache on;
    lua_shared_dict streamer_cache 10m;
    # Set Lua base directory for scripts
    lua_package_path "/opt/racksview/var/lua/?.lua;;";

    # Buffer settings to minimize memory per connection
    output_buffers 1 32k;  # One 32k buffer per connection; adjust based on frame size
    client_body_buffer_size 8k;  # Minimal for headers (MJPEG has no request body)
    client_max_body_size 1m;  # Prevent abuse if POST/PUT requests occur


    server {
        listen       80;
        server_name  racksview; 

        # Serve static files at root (/)
        location / {
            root   /opt/racksview/var/html;
            index  index.html;
        }

        # Proxy raw TCP MJPEG stream with added HTTP headers
        location /stream1 {
            content_by_lua_block {
                local streamer = require("mjpeg_streamer")
                streamer.stream_mjpeg(8013, "--ThisRandomString")
            }
        }
        location /preview1 {
            content_by_lua_block {
                local streamer = require("mjpeg_streamer")
                streamer.stream_mjpeg(8012, "--ThisRandomString")
            }
        }
        location /stream2 {
            content_by_lua_block {
                local streamer = require("mjpeg_streamer")
                streamer.stream_mjpeg(9013, "--ThisRandomString")
            }
        }
        location /preview2 {
            content_by_lua_block {
                local streamer = require("mjpeg_streamer")
                streamer.stream_mjpeg(9012, "--ThisRandomString")
            }
        }

        # List of recordings
        location /video/ {
            alias /opt/racksview/var/video/;
            autoindex on;
            add_before_body /downloads.css; # Add custom CSS before body
            add_after_body /disable-top.js; # Injection of custom JS after body
            autoindex_exact_size off;  # Use human-readable file sizes
        }

        # Serve static files from /events/ directory
        location /downloads/ {
            alias /opt/racksview/var/video/;
            autoindex on;
            add_header Content-Disposition "attachment";
            add_header Content-Type application/octet-stream;
        }

        # Serve status information
        location /status {
            add_header Content-type text/plain;
            content_by_lua_block {
                local statuspage = require("sys_status")
                ngx.say(statuspage.plain_status())
            }
        }

        #logs for debugging
        location /logs/ {
            alias /opt/racksview/log/;
            autoindex on;
        }
    }
}